version: '3.8'

services:
  royal-frontend:
    build: .
    container_name: r-banners-web
    restart: unless-stopped
    ports:
      - "5055:80" # Открываем 3000 порт для Nginx Proxy Manager
    
    # Ограничиваем размер логов, чтобы фронтенд не забил диск сервера
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: royal_frontend_network
    driver: bridge