server {
    listen 80;
    server_name _;
    
    root /usr/share/nginx/html;
    index index.html;

    # Сжатие GZIP для скорости загрузки
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Кэширование статики (картинки, шрифты)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|webp)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}