server {
    listen 80;
    server_name _;
    
    root /usr/share/nginx/html;
    index index.html;

    # Gzip сжатие для экономии трафика и скорости
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    location / {
        # Решаем проблему 404 при обновлении страниц в React Router
        try_files $uri $uri/ /index.html;
    }

    # Кэшируем статику (картинки, стили, скрипты)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|webp)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}